//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsc2020Day2Session2LiveScoreboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitorSubmission()
        {
            this.Scores = new HashSet<Score>();
        }
    
        public int id { get; set; }
        public string areaCompetitionId { get; set; }
        public string competitorId { get; set; }
        public string attempt { get; set; }
        public bool marked { get; set; }
    
        public virtual AreaCompetition AreaCompetition { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
    }
}
